import type { ImageSourcePropType } from "react-native";

// Ícones 3D das conquistas (04/10/2026, enviados pelo Leandro em 7 folhas de 5; recortados por
// scripts/medalhas-recortar.py, fundo e sombra fora). Medalha sem imagem aqui continua com o
// desenho em SVG de medals.ts. Para trocar ou incluir: salvar a folha em assets/medalhas/folhas/,
// pôr os ids em FOLHAS no script, rodar e acrescentar a linha abaixo.
export const MEDALHA_IMG: Record<string, ImageSourcePropType> = {
  "abraco-coletivo": require("../../assets/medalhas/abraco-coletivo.png"),
  "abre-alas": require("../../assets/medalhas/abre-alas.png"),
  "acendeu-a-luz": require("../../assets/medalhas/acendeu-a-luz.png"),
  aclamada: require("../../assets/medalhas/aclamada.png"),
  "agenda-cheia": require("../../assets/medalhas/agenda-cheia.png"),
  "bateu-leque": require("../../assets/medalhas/bateu-leque.png"),
  "bateu-ponto": require("../../assets/medalhas/bateu-ponto.png"),
  cartografa: require("../../assets/medalhas/cartografa.png"),
  "da-casa": require("../../assets/medalhas/da-casa.png"),
  "deu-close": require("../../assets/medalhas/deu-close.png"),
  "deu-o-nome": require("../../assets/medalhas/deu-o-nome.png"),
  "dona-do-pedaco": require("../../assets/medalhas/dona-do-pedaco.png"),
  "eu-conheco": require("../../assets/medalhas/eu-conheco.png"),
  famosinha: require("../../assets/medalhas/famosinha.png"),
  favorita: require("../../assets/medalhas/favorita.png"),
  figurinha: require("../../assets/medalhas/figurinha.png"),
  "icone-local": require("../../assets/medalhas/icone-local.png"),
  inaugurou: require("../../assets/medalhas/inaugurou.png"),
  "influ-do-vale": require("../../assets/medalhas/influ-do-vale.png"),
  "interesse-municipal": require("../../assets/medalhas/interesse-municipal.png"),
  "ja-mora-aqui": require("../../assets/medalhas/ja-mora-aqui.png"),
  "lenda-local": require("../../assets/medalhas/lenda-local.png"),
  "mala-pronta": require("../../assets/medalhas/mala-pronta.png"),
  "nome-na-lista": require("../../assets/medalhas/nome-na-lista.png"),
  "olho-vivo": require("../../assets/medalhas/olho-vivo.png"),
  "ombro-amigo": require("../../assets/medalhas/ombro-amigo.png"),
  "patrimonio-cultural": require("../../assets/medalhas/patrimonio-cultural.png"),
  "patrimonio-tombado": require("../../assets/medalhas/patrimonio-tombado.png"),
  "pode-entrar": require("../../assets/medalhas/pode-entrar.png"),
  "rede-de-apoio": require("../../assets/medalhas/rede-de-apoio.png"),
  "resenha-boa": require("../../assets/medalhas/resenha-boa.png"),
  "sabe-onde-ir": require("../../assets/medalhas/sabe-onde-ir.png"),
  "serviu-tudo": require("../../assets/medalhas/serviu-tudo.png"),
  "tem-opiniao": require("../../assets/medalhas/tem-opiniao.png"),
  "utilidade-publica": require("../../assets/medalhas/utilidade-publica.png"),
};
